export enum DIFFICULTY_LEVELS {
  ENTRY_LEVEL,
  INTERMEDIATE,
  ADVANCED,
  MASTER,
}

interface DEFAULT {
  [DIFFICULTY_LEVELS.ENTRY_LEVEL]: string;
  [DIFFICULTY_LEVELS.INTERMEDIATE]: string;
  [DIFFICULTY_LEVELS.ADVANCED]: string;
  [DIFFICULTY_LEVELS.MASTER]: string;
}

// interface PROFESSION_BASED {
//   [DIFFICULTY_LEVELS.ENTRY_LEVEL]: string;
//   [DIFFICULTY_LEVELS.INTERMEDIATE]: string;
//   [DIFFICULTY_LEVELS.ADVANCED]: string;
//   [DIFFICULTY_LEVELS.MASTER]: string;
// }

export const DEFAULT_VALUES: DEFAULT = {
  [DIFFICULTY_LEVELS.ENTRY_LEVEL]: 'easy',
  [DIFFICULTY_LEVELS.INTERMEDIATE]: 'intermediate',
  [DIFFICULTY_LEVELS.ADVANCED]: 'advanced',
  [DIFFICULTY_LEVELS.MASTER]: 'master',
};

export const PROFESSION_BASED_VALUES: DEFAULT = {
  [DIFFICULTY_LEVELS.ENTRY_LEVEL]: '0-2 years',
  [DIFFICULTY_LEVELS.INTERMEDIATE]: '3-5 years',
  [DIFFICULTY_LEVELS.ADVANCED]: '6-10 years',
  [DIFFICULTY_LEVELS.MASTER]: '10+ years',
};
