import { NumberInput, Select, Stack, TagsInput } from '@mantine/core';
import { GetInputPropsReturnType } from '@mantine/form/lib/types';

interface FocusAreaProps {
  data: string[];
  value: string | null | undefined;
  onChange: (value: string | null) => void;
}

interface QuizAttrSectionProps {
  topicsProps: GetInputPropsReturnType;
  quesProps: GetInputPropsReturnType;
  focusAreaProps: FocusAreaProps;
  showIncludeExclude: boolean;
  showExclusive: boolean;
  includeProps: GetInputPropsReturnType;
  excludeProps: GetInputPropsReturnType;
  exclusiveProps: GetInputPropsReturnType;
}

export default function QuizAttributeSection({
  topicsProps,
  quesProps,
  focusAreaProps,
  showIncludeExclude,
  showExclusive,
  includeProps,
  excludeProps,
  exclusiveProps,
}: QuizAttrSectionProps) {
  return (
    <Stack>
      <NumberInput
        label="Number of Topics (1-3)"
        clampBehavior="strict"
        min={1}
        max={3}
        {...topicsProps}
      />
      <NumberInput
        label="Number of Questions per Topic (1-2)"
        clampBehavior="strict"
        min={1}
        max={2}
        {...quesProps}
      />
      <Select
        mt="1rem"
        label="OPTIONAL: Topic Curation"
        placeholder="OPTIONAL: allows for generating more selective questions"
        description="Can deselect by clicking option again"
        data={focusAreaProps.data}
        value={focusAreaProps.value}
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
        onChange={(value, _option) => focusAreaProps.onChange(value)}
      />
      {showIncludeExclude && (
        <>
          <TagsInput
            mt="xl"
            label="OPTIONAL: Requests specific topics to be INCLUDED"
            placeholder="USE ENTER to submit"
            description="Requests that topics listed here inform the topics generated by AI (max 3)"
            defaultValue={[]}
            maxTags={3}
            clearable
            {...includeProps}
          />
          <TagsInput
            label="OPTIONAL: Requests specific topics to be EXCLUDED"
            placeholder="USE ENTER to submit"
            description="Requests that topics listed here are avoided by AI (max 10)"
            defaultValue={[]}
            maxTags={10}
            clearable
            {...excludeProps}
          />
        </>
      )}
      {showExclusive && (
        <TagsInput
          mt="xl"
          label="OPTIONAL: Requests questions EXCLUSIVELY around these focus areas"
          placeholder="USE ENTER to submit"
          description="Requests questions on these topics, alone (1-3)"
          defaultValue={[]}
          maxTags={3}
          clearable
          {...exclusiveProps}
        />
      )}
    </Stack>
  );
}
